(add-to-list 'load-path "~/.emacs.d/lisp/customize")
(require 'settings)
(require 'theme)
(require 'init-dashboard)
(require 'init-modeline)
(require 'org-mode)
(require 'init-projectile)
(require 'init-lvy)
(require 'init-lsp)
(require 'init-treemacs)
(require 'init-git)
(require 'init-vterm)
(require 'init-proxy)
